name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set Environment Variables
      shell: powershell
      run: |
        $env:M2_HOME = 'C:\Users\YAvanthika\Downloads\apache-maven-3.9.8'
        $env:JAVA_HOME = 'C:\Program Files\Java\jdk-21'
        $env:PATH = "$env:M2_HOME\bin;$env:JAVA_HOME\bin;$env:PATH"

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Check Maven Version
      shell: powershell
      run: |
        $env:M2_HOME = 'C:\Users\YAvanthika\Downloads\apache-maven-3.9.8'
        $env:JAVA_HOME = 'C:\Program Files\Java\jdk-21'
        $env:PATH = "$env:M2_HOME\bin;$env:JAVA_HOME\bin;$env:PATH"
        mvn --version

    - name: Build with Maven
      shell: powershell
      run: |
        $env:M2_HOME = 'C:\Users\YAvanthika\Downloads\apache-maven-3.9.8'
        $env:JAVA_HOME = 'C:\Program Files\Java\jdk-21'
        $env:PATH = "$env:M2_HOME\bin;$env:JAVA_HOME\bin;$env:PATH"
        mvn -B package --file pom.xml

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          target/*.jar

    - name: Create Git Tag
      id: create_tag
      shell: powershell
      run: |
        $TAG_NAME = "v1.$($env:GITHUB_RUN_NUMBER)"
        echo "::set-output name=TAG_NAME::$TAG_NAME"
        git tag $TAG_NAME
        git push origin $TAG_NAME
      env:
        GITHUB_RUN_NUMBER: ${{ github.run_number }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
        release_name: Release ${{ steps.create_tag.outputs.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Zip build artifacts
      shell: powershell
      run: Compress-Archive -Path target/* -DestinationPath build/build-artifacts.zip

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/build-artifacts.zip
        asset_name: build-artifacts.zip
        asset_content_type: application/zip
